### ISSUE TITLE
mapping values are not allowed in this context

### ISSUE THREAD

**Issue by johentsch** [openjournals/openjournals-draft-action#16]
Hi folks,

I'm in the process of hacking my JOSS paper together. My first test `paper.md` compiled perfectly but now with the latest commit the action failed with the error 

```
YAML parse exception at line 12, column 9:
mapping values are not allowed in this context
```

which is kind of funny because the YAML file had actually not changed since the last time when it worked. The indicated position is this one:

```
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
        ^
```

Since the YML file itself has not changed, could it be due to the [commit to paper.md](https://github.com/johentsch/ms3/commit/9c296b017b8913e3632674891097ef3b3879b7d6) itself? It comments out a section with `<!-- -->` HTML syntax, could this be the issue?

Here is the [list of latest runs](https://github.com/johentsch/ms3/actions/workflows/draft-pdf.yml) for inspection.

Thank you in advance!
