### ISSUE TITLE
Action Failing

### ISSUE THREAD

**Issue by ttortorici** [openjournals/openjournals-draft-action#31]
I am getting warnings for each of my citations like this:

`Warning:  Citeproc: citation [citation-name] not found`

I have `bibliography: paper.bib` in the header of paper.md, and the citations are in my paper.bib file; eg:

```
@book{schaum,
   author = {Murray R. Spiegel and Seymour Lipschutz and John Liu},
   edition = {4th},
   publisher = {McGraw-Hill Education},
   title = {Mathematical Handbook of Formulas and Tables},
   year = {2012},
}
```

my ".github/workflows/draft-pdf.yml" file is:

```
name: Draft PDF
on:
  push:
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Open Journals PDF Generator
        uses: openjournals/openjournals-draft-action@v.1.0
        with:
          journal: joss
          paper-path: paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf
```

and both paper.md and paper.bib are in a directory called /paper
