### ISSUE TITLE
paper draft pdf fails with inara

### ISSUE THREAD

**Issue by villaa** [openjournals/openjournals-draft-action#9]
So I see recently the repository has switched over to inara. Using the template that is still on the front-facing README, I am getting errors in the build like: `Could not find data file templates/latex.template' ,  [see this](https://github.com/villano-lab/galactic-spin-W1/runs/5426795494?check_suite_focus=true) repository. 

Our build .yml file is:

```
on: [push]
  
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: jose
          # This should be the path to the paper within your repo.
          paper-path: paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: paper/paper.pdf
```

Do we need to update this file? Can someone suggest a course of action?
